#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <ctype.h>

/*	This is the random number generator that can be used universally throughout the whole program
	Precondition:	The minimum and maximum values must be defined
	@param min is the minimum value of the range of random numbers to be generated
	@param max is the maximum value of the range of random numbers to be generated
*/
int giveRandNums(int min, int max) {
	
	// Find the random number in the range [min, max]
    int rd_num = rand() % (max - min + 1) + min;
    
    return rd_num;
}

/*	This function prompts the user to press a user-defined key so they can roll the virtual die
	Precondition:	User can input any character found on a standard keyboard, but they must press enter afterwards
	@param key_press this is the player's input
*/
void promptRoll() {
    char key_press; 
    
	scanf("%*[^\n]%*c");		//Reads and discards any old inputs
    
	printf("\n");
    printf("Ready to roll the dice?\nPress ANY key (and then Enter) to roll the die...");
    
    // In case the user SOMEHOW messes up
    if (scanf(" %c", &key_press) != 1) {
        printf("\nInput error occurred.\n");
    }    
    
	scanf("%*[^\n]%*c");		//Reads and discards any old inputs
    
	printf("\n");
}

/*	This is the function that allows the user to roll a die and get a value between 1 and 6
	Precondition:	Minimum value must be 1 and the Maximum value must be 6
	@param nRoll is the random value (between 1 and 6) generated by rolling the die
	@param min is the minimum value of the range of random numbers to be generated
	@param max is the maximum value of the range of random numbers to be generated 
*/
int diceRoll(){
	int nRoll, min = 1, max = 6;	//Define the range of the values given by a die (1 through 6)
	
	nRoll = giveRandNums(min, max);	//randomly generate a value and assign it to nRoll
	
	printf("\n\n=======================================================\n\n");
	printf("The number rolled on the die is: %d\n", nRoll);
	printf("You will now have a chance to move up to %d space(s)!\n\n", nRoll);	
	printf("=======================================================\n\n");
	
	return nRoll;	//return the value of the dice roll
}

/*	This is the that punishes a player if they get an answer wrong
	Precondition: 	Player gets the answer wrong
	@param score is the current score of the player
	@param get_punished is a randomly generated value between 1 and 3 used to decrease the players score
	@param min is the minimum value of the range of random numbers to be generated
	@param max is the maximum value of the range of random numbers to be generated 
*/
int playerPunish(int score){
	int get_punished;
	int min = 1, max = 3;
	
	get_punished = giveRandNums(min, max);
	
	score = score - get_punished;	//Subtracts the player's score by either 1, 2, or 3
	printf("\n\n\t>>> You have unfortunately moved down %d spaces... <<<\n\n", get_punished);	//Informs the player of how much has been deducted
	
	return score;	//returns the deducted score after the player is punished
}
